stages:
  prepare_data:
    cmd: python src/features/build_features.py
    deps:
    - src/features/build_features.py

  train:
    cmd: python src/models/train_model.py 
    deps:
    - src/models/train_model.py
    - src/features/build_features.py
    
  evaluate:
    cmd: python src/models/predict_model.py
    deps:
    - models/bike_model.h5
    - src/models/predict_model.py
    - src/features/build_features.py
    outs:
    - reports/figures/prediction.png
   
    metrics:
    - reports/score.json:
        cache: false
